# Site settings
title: Adriane's Blog
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my personal blog where I share thoughts, ideas, and experiences.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://adriane888.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Social links
github_username: adriane888

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/