title: Different Error
email: adriane.smith888@gmail.com
description: >-
  A blog about ...me, Adriane Smith, a DevOps Engineer passionate about people first, technology second.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://adriane888.github.io"
theme: minima
navigation:
  - title: "About Me"
    url: "/about/"
  - title: "Resume"
    url: "/resume/"
  - title: "Posts"
    url: "/posts/"
  - title: "Categories"
    url: "/categories/"
